# Group Affective Behavior (GAB) and Hostile Affect Development (E.26)

In [1]:
# GAB --> balance of positive and negative sentiment in conversation
# subtract negativity from positivity (discard neutrality)

# get all positive_bert and negative_bert scores for a given conversation from chat level ouput

import pandas as pd

df = pd.read_csv('../output/csopII_output_chat_level.csv', encoding='mac_roman')
df

FileNotFoundError: [Errno 2] No such file or directory: '../output/csopII_output_chat_level.csv'

In [4]:
def group_affective_behavior(chat_df):

    # gab = chat_df[['conversation_num']].drop_duplicates()
    gab = []

    for conv in chat_df.groupby(['conversation_num']):
        # print(conv[1]['positive_bert'])

        gab.append(conv[1]['positive_bert'].sum() - conv[1]['negative_bert'].sum())
    
    return pd.DataFrame({'gab':gab})

group_affective_behavior(df)

          gab
0    1.310083
1    0.131912
2    0.131912
3    0.131912
4    0.131912
..        ...
957 -0.445389
958  0.131912
959  0.131912
960 -1.060671
961  0.131912

[962 rows x 1 columns]

In [3]:
# Hostile Affect --> number of occurrences of "hostile" behavior
# Contempt (" belittle, hurt, or humiliate"), criticism ("highlight [...] as inherently defective"), stonewalling ("communicate an unwillingness to listen or respond"), defensiveness ("deflect responsibility or blame")

# Chat level feature, evaluate toxicity of each message
# Potential tools --> Perspective API, BERT toxic language classification, RECAST model

In [70]:
# Perspective API Key: AIzaSyBvApFd8k1e0VaYO9iGmXlXUO8525Ln5X4
# Limitation --> 1 query/second


from googleapiclient import discovery
import json

API_KEY = 'AIzaSyBvApFd8k1e0VaYO9iGmXlXUO8525Ln5X4'

client = discovery.build(
  "commentanalyzer",
  "v1alpha1",
  developerKey=API_KEY,
  discoveryServiceUrl="https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1",
  static_discovery=False,
)

def hostile_instances(chat):
  print(type(chat))
  if chat:
    analyze_request = {
      'comment': { 'text': chat },
      'requestedAttributes': {'TOXICITY': {}},
      'languages': ["en"]
    }

    response = client.comments().analyze(body=analyze_request).execute()
    return response['attributeScores']['TOXICITY']['summaryScore']['value']
  # print(f"toxicity: {response['attributeScores']['TOXICITY']['summaryScore']['value']}")

In [71]:
import re

def preprocess_conversation_columns(df):
	# remove all special characters from df
	df.columns = df.columns.str.replace('[^A-Za-z0-9_]', '', regex=True)
	
	# If data is grouped by batch/round, add a conversation num
	if {'batch_num', 'round_num'}.issubset(df.columns):
		df['conversation_num'] = df.groupby(['batch_num', 'round_num']).ngroup()
		df = df[df.columns.tolist()[-1:] + df.columns.tolist()[0:-1]] # make the new column first

	return(df)

def preprocess_text(text):
  	# For each individual message: preprocess to remove anything that is not an alphabet or number from the string
	return(re.sub(r"[^a-zA-Z0-9 ]+", '',text).lower())

In [73]:
df = pd.read_csv('./data/raw_data/csopII_conversations_withblanks.csv', encoding='mac_roman')
df = preprocess_conversation_columns(df)
df["message"] = df["message"].astype(str).apply(preprocess_text)
df

,conversation_num,batch_num,vis_img,int_verb,ort_img,rep_man,soc_pers,team_size,difficulty,score,duration,efficiency,speaker_nickname,message,timestamp
0,rHPaiuXkM3Ss4rEsW_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],586.0,107.0,5.476636,oJLD2kfcwGyXkfCeH,can we get d to the highest score,2021-02-26T19:11:21.474Z
1,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,406.0,1.376847,6QvNn8wdCyviKCjiv,looks good,2021-02-26T19:22:32.695Z
2,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,406.0,1.376847,6qP7EcqvYQL4gmrAX,i like it,2021-02-26T19:23:14.467Z
3,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,406.0,1.376847,NMkPLqERKzTTMqw5Y,it looks good to me,2021-02-26T19:23:20.650Z
4,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,406.0,1.376847,6QvNn8wdCyviKCjiv,stop changing it,2021-02-26T19:23:52.111Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4614,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,86.0,8.383721,hNDxbBcuh8b56WEGD,same,2021-09-20T18:12:24.809Z
4615,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,86.0,8.383721,roWwgXBwsM2kWSrG2,lol,2021-09-20T18:12:24.894Z
4616,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,86.0,8.383721,uAWmy8vGcsY6RGDJe,i agree blue,2021-09-20T18:12:27.368Z
4617,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,86.0,8.383721,kQY7q8Py3kgANA29w,this looks good,2021-09-20T18:12:31.012Z
4618,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,86.0,8.383721,roWwgXBwsM2kWSrG2,yep,2021-09-20T18:12:41.063Z

In [74]:
# df['toxicity'] = df['message'].apply(hostile_instances)
# df['toxicity']
df['message'].apply(hostile_instances)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

KeyboardInterrupt:

In [27]:
# BERT Language classification - time expense!

from detoxify import Detoxify
results = Detoxify('original').predict('example text')
print(results)

Downloading: "https://github.com/unitaryai/detoxify/releases/download/v0.1-alpha/toxic_original-c1212f89.ckpt" to /Users/agshruti/.cache/torch/hub/checkpoints/toxic_original-c1212f89.ckpt
100%|██████████| 418M/418M [01:02<00:00, 6.98MB/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]