# Group Affective Behavior (GAB) and Hostile Affect Development (E.26)

In [3]:
# GAB --> balance of positive and negative sentiment in conversation
# subtract negativity from positivity (discard neutrality)

# get all positive_bert and negative_bert scores for a given conversation from chat level ouput

import pandas as pd

df = pd.read_csv('../output/csopII_output_chat_level.csv', encoding='mac_roman')
df

,conversation_num,batch_num,vis_img,int_verb,ort_img,rep_man,soc_pers,team_size,difficulty,score,...,1st_person_start,2nd_person,2nd_person_start,indirect_(greeting),direct_question,direct_start,haspositive,hasnegative,subjunctive,indicative
0,rHPaiuXkM3Ss4rEsW_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],586.0,...,0,0,0,0,0,0,0,0,0,0
1,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,...,0,0,0,0,0,0,1,0,0,0
2,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,...,1,0,0,0,0,0,1,0,0,0
3,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,...,0,0,0,0,0,0,1,0,0,0
4,dArSAcrzmb9bR6Pug_easy,1,High,High,High,High,High,5,Easy [Corresponds to 'Hard' in PNAS],559.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4614,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,...,0,0,0,0,0,0,0,0,0,0
4615,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,...,0,0,0,0,0,0,0,0,0,0
4616,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,...,1,0,0,0,0,0,0,0,0,0
4617,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,...,0,0,0,0,0,0,1,0,0,0
4618,PP8QdaXDj8e7GBPT3_hard,5,Mixed,Low,Low,Low,High,8,Hard [Corresponds to 'Super Hard' in PNAS],721.0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
def group_affective_behavior(chat_df):

    # gab = chat_df[['conversation_num']].drop_duplicates()
    gab = []

    for conv in chat_df.groupby(['conversation_num']):
        # print(conv[1]['positive_bert'])

        gab.append(conv[1]['positive_bert'].sum() - conv[1]['negative_bert'].sum())
    
    return pd.DataFrame({'gab':gab})

group_affective_behavior(df)

          gab
0    1.310083
1    0.131912
2    0.131912
3    0.131912
4    0.131912
..        ...
957 -0.445389
958  0.131912
959  0.131912
960 -1.060671
961  0.131912

[962 rows x 1 columns]

In [3]:
# Hostile Affect --> number of occurrences of "hostile" behavior
# Contempt (" belittle, hurt, or humiliate"), criticism ("highlight [...] as inherently defective"), stonewalling ("communicate an unwillingness to listen or respond"), defensiveness ("deflect responsibility or blame")

# Chat level feature, evaluate toxicity of each message
# Potential tools --> Perspective API, BERT toxic language classification, RECAST model

In [5]:
# Perspective API Key: AIzaSyBvApFd8k1e0VaYO9iGmXlXUO8525Ln5X4
# Limitation --> 1 query/second

from googleapiclient import discovery
import json

API_KEY = 'AIzaSyBvApFd8k1e0VaYO9iGmXlXUO8525Ln5X4'

client = discovery.build(
  "commentanalyzer",
  "v1alpha1",
  developerKey=API_KEY,
  discoveryServiceUrl="https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1",
  static_discovery=False,
)

def hostile_instances(chat):

  analyze_request = {
    'comment': { 'text': chat },
    'requestedAttributes': {'TOXICITY': {}}
  }

  response = client.comments().analyze(body=analyze_request).execute()
  return response['attributeScores']['TOXICITY']['summaryScore']['value']
  # print(f"toxicity: {response['attributeScores']['TOXICITY']['summaryScore']['value']}")

In [10]:
df = pd.read_csv('../data/raw_data/csopII_conversations_withblanks.csv', encoding='mac_roman')
# df['toxicity'] = df['message'].apply(hostile_instances)
# df['toxicity']
df['message'].apply(hostile_instances)

HttpError: <HttpError 400 when requesting https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key=AIzaSyBvApFd8k1e0VaYO9iGmXlXUO8525Ln5X4&alt=json returned "Attribute TOXICITY does not support request languages: und". Details: "[{'@type': 'type.googleapis.com/google.commentanalyzer.v1alpha1.Error', 'errorType': 'LANGUAGE_NOT_SUPPORTED_BY_ATTRIBUTE', 'languageNotSupportedByAttributeError': {'detectedLanguages': ['und'], 'attribute': 'TOXICITY'}}]">

In [27]:
# BERT Language classification - time expense!

from detoxify import Detoxify
results = Detoxify('original').predict('example text')
print(results)

Downloading: "https://github.com/unitaryai/detoxify/releases/download/v0.1-alpha/toxic_original-c1212f89.ckpt" to /Users/agshruti/.cache/torch/hub/checkpoints/toxic_original-c1212f89.ckpt
100%|██████████| 418M/418M [01:02<00:00, 6.98MB/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]